<?php
	global $rw_text;

	$rw_text = array(
		'email'                                       => __( 'Email', 'rating-widget' ),
		'oops'                                        => __( 'Oops', 'rating-widget' ),
		'edit'                                        => _x( 'Edit', 'button label to edit a value', 'rating-widget' ),
		'site-id'                                     => __( 'Site ID', 'rating-widget' ),
		'no-id'                                       => __( 'No ID', 'rating-widget' ),
		'free-uppercase'                              => __( 'FREE', 'rating-widget' ),
		'free'                                        => __( 'Free', 'rating-widget' ),
		'purchase'                                    => _x( 'Purchase', 'verb, as buy something', 'rating-widget' ),
		'public-key'                                  => _x( 'Public Key', 'as encryption key', 'rating-widget' ),
		'secret-key'                                  => _x( 'Secret Key', 'as encryption key', 'rating-widget' ),
		'no-secret'                                   => _x( 'No Secret', 'as secret encryption key missing', 'rating-widget' ),
		'plan'                                        => _x( 'Plan', 'as product pricing plan', 'rating-widget' ),
		'thumbs'                                      => __( 'Thumbs', 'rating-widget' ),
		'star'                                        => __( 'Star', 'rating-widget' ),
		'show-thumbs'                                 => __( 'Show Thumbs', 'rating-widget' ),
		'tiny'                                        => __( 'Tiny', 'rating-widget' ),
		'small'                                       => __( 'Small', 'rating-widget' ),
		'medium'                                      => _x( 'Medium', 'as medium size', 'rating-widget' ),
		'large'                                       => __( 'Large', 'rating-widget' ),
		'faq'                                         => __( 'FAQ', 'rating-widget' ),
		'settings'                                    => __( 'Settings', 'rating-widget' ),
		'blog'                                        => __( 'Blog', 'rating-widget' ),
		'element'                                     => __( 'Element', 'rating-widget' ),
		'category'                                    => __( 'Category', 'rating-widget' ),
		'page'                                        => __( 'Page', 'rating-widget' ),
		'pages'                                       => __( 'Pages', 'rating-widget' ),
		'posts'                                       => __( 'Posts', 'rating-widget' ),
		'blog-post'                                   => __( 'Blog Post', 'rating-widget' ),
		'blog-posts'                                  => __( 'Blog Posts', 'rating-widget' ),
		'front-page-posts'                            => __( 'Front Page Posts', 'rating-widget' ),
		'front-page-post'                             => __( 'Front Page Post', 'rating-widget' ),
		'comment'                                     => __( 'Comment', 'rating-widget' ),
		'comments'                                    => __( 'Comments', 'rating-widget' ),
		'product'                                     => __( 'Product', 'rating-widget' ),
		'products'                                    => __( 'Products', 'rating-widget' ),
		'collection-product'                          => __( 'Collection Product', 'rating-widget' ),
		'topics'                                      => __( 'Topics', 'rating-widget' ),
		'user'                                        => __( 'User', 'rating-widget' ),
		'users'                                       => __( 'Users', 'rating-widget' ),
		'anonymous'                                   => __( 'Anonymous', 'rating-widget' ),
		'registered'                                  => __( 'Registered', 'rating-widget' ),
		'summary'                                     => __( 'Summary', 'rating-widget' ),
		'advanced'                                    => __( 'Advanced', 'rating-widget' ),
		'rating'                                      => __( 'Rating', 'rating-widget' ),
		'ratings'                                     => __( 'Ratings', 'rating-widget' ),
		'type'                                        => __( 'Type', 'rating-widget' ),
		'font'                                        => __( 'Font', 'rating-widget' ),
		'layout'                                      => __( 'Layout', 'rating-widget' ),
		'background'                                  => __( 'Background', 'rating-widget' ),
		'color'                                       => __( 'Color', 'rating-widget' ),
		'style'                                       => __( 'Style', 'rating-widget' ),
		'hover'                                       => __( 'Hover', 'rating-widget' ),
		'top'                                         => __( 'Top', 'rating-widget' ),
		'bottom'                                      => __( 'Bottom', 'rating-widget' ),
		'middle'                                      => __( 'Middle', 'rating-widget' ),
		'left'                                        => __( 'Left', 'rating-widget' ),
		'center'                                      => __( 'Center', 'rating-widget' ),
		'right'                                       => _x( 'Right', 'as right side', 'rating-widget' ),
		'voting-frequency-settings'                   => __( 'Voting Frequency Settings', 'rating-widget' ),
		'theme'                                       => __( 'Theme', 'rating-widget' ),
		'language'                                    => __( 'Language', 'rating-widget' ),
		'size'                                        => __( 'Size', 'rating-widget' ),
		'text'                                        => __( 'Text', 'rating-widget' ),
		'read-only'                                   => __( 'Read Only', 'rating-widget' ),
		'advanced-settings'                           => __( 'Advanced Settings', 'rating-widget' ),
		'name'                                        => __( 'Name', 'rating-widget' ),
		'votes'                                       => _x( 'Votes', 'noun - plural of vote', 'rating-widget' ),
		'vote'                                        => _x( 'Vote', 'noun', 'rating-widget' ),
		'add-ons'                                     => __( 'Add Ons', 'rating-widget' ),
		'reports'                                     => __( 'Reports', 'rating-widget' ),
		'affiliation'                                 => __( 'Affiliation', 'rating-widget' ),
		'top-rated-widget'                            => __( 'Top-Rated Widget', 'rating-widget' ),
		'activity-updates'                            => __( 'Activity Updates', 'rating-widget' ),
		'activity-comments'                           => __( 'Activity Comments', 'rating-widget' ),
		'activity-blog-posts'                         => __( 'Activity Blog Posts', 'rating-widget' ),
		'activity-blog-comments'                      => __( 'Activity Blog Comments', 'rating-widget' ),
		'user-profiles'                               => __( 'Users Profiles', 'rating-widget' ),
		'forum-posts'                                 => __( 'Forum Posts', 'rating-widget' ),
		'activity-forum-posts'                        => __( 'Activity Forum Posts', 'rating-widget' ),
		'add-widget-now'                              => __( 'Add Widget Now!', 'rating-widget' ),
		'install-verb'                                => _x( 'Install', 'verb', 'rating-widget' ),
		'rating-type'                                 => __( 'Rating Type', 'rating-widget' ),
		'post-type'                                   => __( 'Post Type', 'rating-widget' ),
		'go-to'                                       => _x( 'Go to', 'verb', 'rating-widget' ),
		'votes-timeline'                              => _x( 'Votes Timeline', 'title of a chart representing users\' votes', 'rating-widget' ),
		'no-sufficient-permissions'                   => __( 'You do not have sufficient permissions to access this page.', 'rating-widget' ),
		'settings-successfully-saved'                 => __( 'Settings successfully saved.', 'rating-widget' ),
		'add-label'                                   => __( 'Add Label', 'rating-widget' ),
		'save-changes'                                => __( 'Save Changes', 'rating-widget' ),
		'save'                                        => _x( 'Save', 'as save changes', 'rating-widget' ),
		'cancel'                                      => _x( 'Cancel', 'as cancel changes', 'rating-widget' ),
		'delete'                                      => __( 'Delete', 'rating-widget' ),
		'close'                                       => __( 'Close', 'rating-widget' ),
		'upgrade-now'                                 => __( 'Upgrade Now!', 'rating-widget' ),
		'follow'                                      => _x( 'Follow', 'as twitter follow', 'rating-widget' ),
		'follow-twitter'                              => __( 'Follow us on Twitter', 'rating-widget' ),
		'like-on-facebook'                            => __( 'Like us on Facebook', 'rating-widget' ),
		'add-criteria-rating'                         => _x( 'Add Rating / Criteria', 'as add new criteria for a review', 'rating-widget' ),
		'show-summary-rating'                         => _x( 'Show Summary Rating', 'summary rating represent the average rate of all the rated criteria', 'rating-widget' ),
		'learn-more'                                  => __( 'Learn More', 'rating-widget' ),
		'activate'                                    => __( 'Activate', 'rating-widget' ),
		'deactivate'                                  => __( 'Deactivate', 'rating-widget' ),
		'active'                                      => _x( 'Active', 'active mode', 'rating-widget' ),
		'inactivate'                                  => __( 'In-Activate', 'rating-widget' ),
		'ratingwidget-account'                        => __( 'RatingWidget Account', 'rating-widget' ),
		'ratingwidget-options'                        => __( 'RatingWidget Options', 'rating-widget' ),
		/* Multi-Rating Options
		-----------------------------------------------------------------------*/
		'multi-rating-options'                        => __( 'Multi-Rating Options', 'rating-widget' ),
		'multi-rating-options_hide-info'              => __( 'Hide Info Bubble', 'rating-widget' ),
		'multi-rating-options_author-rating'          => __( 'Author Rating (read-only for visitors)', 'rating-widget' ),
		/* Account
		-----------------------------------------------------------------------*/
		'account-actions'                             => __( 'Account Actions', 'rating-widget' ),
		'what-is-your'                                => __( 'What is your %s?', 'rating-widget' ),
		'default-settings'                            => __( 'Default Settings', 'rating-widget' ),
		'default-settings_desc'                       => __( 'Restore the default factory settings.', 'rating-widget' ),
		'default-settings_confirm'                    => __( 'Are you sure you want to restore to default settings?', 'rating-widget' ),
		'clear-cache'                                 => __( 'Clear Cache', 'rating-widget' ),
		'clear-cache_desc'                            => __( 'Clear plugin\'s cache, including the Top-Rated Widget cache.', 'rating-widget' ),
		'clear-ratings'                               => __( 'Clear Ratings', 'rating-widget' ),
		'clear-ratings_desc'                          => __( 'Delete all ratings and votes.', 'rating-widget' ),
		'clear-ratings_confirm'                       => __( 'Are you sure you want to delete all the ratings and votes?', 'rating-widget' ),
		'start-fresh'                                 => __( 'Start Fresh', 'rating-widget' ),
		'start-fresh_desc'                            => __( 'Start fresh as if you just installed the plugin. Delete all your ratings and votes, and restore the default factory settings.', 'rating-widget' ),
		'start-fresh_confirm'                         => __( 'Are you sure you want to delete all the ratings and votes, and restore to default factory settings?', 'rating-widget' ),
		/* Marketing
		-----------------------------------------------------------------------*/
		'upgrade-to-pro'                              => __( 'Upgrade to Professional', 'rating-widget' ),
		'upgrade_top-rated-table'                     => __( 'Upgrade to Professional for 50 Items', 'rating-widget' ),
		'upgrade_criteria-limit'                      => __( 'Upgrade to Professional for Unlimited Criteria', 'rating-widget' ),
		'upgrade_reports'                             => __( 'Upgrade now to get reports and more Professional Features', 'rating-widget' ),
		'dummy-report-marketing'                      => __( 'Reports provides you with an analytical overview of your rated elements in one page. Here, you can gain an understanding of how interesting and attractive your blog elements (e.g. posts, pages), how active your users, and check the segmentation of the votes.', 'rating-widget' ),
		/* Top-Rated Widget
		-----------------------------------------------------------------------*/
		'toprated_increase-retention'                 => __( 'Increase User Retention and Page Views', 'rating-widget' ),
		'toprated_stay-longer'                        => __( 'With the Top-Rated Sidebar Widget readers will stay on your site for a longer period of time.', 'rating-widget' ),
		'how'                                         => _x( 'How', 'adverb - in what way or manner; by what means.', 'rating-widget' ),
		'toprated_how-desc'                           => __( 'Expose your readers to the top rated posts on site that they might not have otherwise noticed and increase your chance to reduce the bounce rate.', 'rating-widget' ),
		'what'                                        => _x( 'What', 'adverb - title to describe the product', 'rating-widget' ),
		'toprated_what-desc'                          => __( 'The Top-Rated Widget is a beautiful sidebar widget containing the top rated posts on your blog.', 'rating-widget' ),
		'new'                                         => __( 'New', 'rating-widget' ),
		'toprated_new-desc'                           => __( 'Thumbnails: a beautiful new thumbnail display, for themes which use post thumbnails (featured images).', 'rating-widget' ),
		'performance'                                 => __( 'Performance', 'rating-widget' ),
		'toprated_performance-desc'                   => __( 'The widget is performant, caching the top posts and featured images\' thumbnails as your site is visited.', 'rating-widget' ),
		'top-rated-posts'                             => __( 'A list of your top rated posts.', 'rating-widget' ),
		'top-rated'                                   => __( 'Top Rated', 'rating-widget' ),
		's-created-in'                                => __( '%s created in:', 'rating-widget' ),
		'title-max-length'                            => __( 'Title Max Length', 'rating-widget' ),
		''                                            => __( '', 'rating-widget' ),
		/* Reports
		-----------------------------------------------------------------------*/
		'rating-report'                               => __( 'Rating Report', 'rating-widget' ),
		'show-rows'                                   => _x( 'Show rows', 'label of a dropdown list to select the number of rows that the table can show', 'rating-widget' ),
		'order'                                       => _x( 'Order', 'Ascending or Descending', 'rating-widget' ),
		'orderby'                                     => __( 'Order By', 'rating-widget' ),
		'best'                                        => __( 'best', 'rating-widget' ),
		'worst'                                       => __( 'Worst', 'rating-widget' ),
		'ascending'                                   => __( 'Ascending', 'rating-widget' ),
		'descending'                                  => __( 'descending', 'rating-widget' ),
		'title'                                       => __( 'Title', 'rating-widget' ),
		'widget-title'                                => __( 'Widget Title', 'rating-widget' ),
		'id'                                          => _x( 'ID', 'identifier', 'rating-widget' ),
		'rating-id'                                   => __( 'Rating ID', 'rating-widget' ),
		'user-id'                                     => __( 'User ID', 'rating-widget' ),
		'device-id'                                   => __( 'Device ID', 'rating-widget' ),
		'ip'                                          => _x( 'IP', 'as IP address', 'rating-widget' ),
		'start-date'                                  => __( 'Start Date', 'rating-widget' ),
		'last-updated'                                => __( 'Last Update', 'rating-widget' ),
		'created'                                     => __( 'Created', 'rating-widget' ),
		'created-in'                                  => __( 'Created In', 'rating-widget' ),
		'show'                                        => _x( 'Show', 'verb', 'rating-widget' ),
		'previous'                                    => _x( 'Previous', 'as previous page', 'rating-widget' ),
		'next'                                        => _x( 'Next', 'as next page', 'rating-widget' ),
		'date'                                        => _x( 'Date', 'the day of the month or year as specified by a number.', 'rating-widget' ),
		'date-range'                                  => _x( 'Date Range', 'range of days in a calendar.', 'rating-widget' ),
		'average-rate'                                => __( 'Average Rate', 'rating-widget' ),
		'eg'                                          => _x( 'e.g %s', 'for example', 'rating-widget' ),
		'no-ratings'                                  => __( 'No ratings here.', 'rating-widget' ),
		'no-votes'                                    => __( 'No votes here.', 'rating-widget' ),
		'rate-noun'                                   => _x( 'Rate', 'noun - a measure, quantity, or frequency, typically one measured against some other quantity or measure.', 'rating-widget' ),
		/* Ask to review on WordPress
-----------------------------------------------------------------------*/
		'rate-ask_message'                            => __( "Hey, I noticed you just crossed the %d votes on RatingWidget - that's awesome! Could you please do me a BIG favor and give it a 5-star rating on WordPress? Just to help us spread the word and boost our motivation.", 'rating-widget' ),
		'rate-ask_ok'                                 => __( 'Ok, you deserve it', 'rating-widget' ),
		'rate-ask_already-did'                        => __( 'I already did', 'rating-widget' ),
		'rate-ask_no'                                 => __( 'No, not good enough', 'rating-widget' ),
		'preview-rate-ask'                            => __( 'Like it?', 'rating-widget' ),
		'preview-rate-ask_title'                      => __( 'Support the plugin with ★ 5 Stars', 'rating-widget' ),
		/* Voting Frequency
		-----------------------------------------------------------------------*/
		'once'                                        => _x( 'Once', 'as one time', 'rating-widget' ),
		'daily'                                       => _x( 'Daily', 'as once a day', 'rating-widget' ),
		'weekly'                                      => _x( 'Weekly', 'as once a week', 'rating-widget' ),
		'monthly'                                     => _x( 'Monthly', 'as once a month', 'rating-widget' ),
		'annually'                                    => _x( 'Annually', 'as once a year', 'rating-widget' ),
		'unlimited'                                   => __( 'Unlimited', 'rating-widget' ),
		'once_desc'                                   => __( 'user can vote only once per rating', 'rating-widget' ),
		'daily_desc'                                  => __( 'user can vote once a day for every rating', 'rating-widget' ),
		'weekly_desc'                                 => __( 'user can vote once a week for every rating', 'rating-widget' ),
		'monthly_desc'                                => __( 'user can vote once a month (30 days) for every rating', 'rating-widget' ),
		'annually_desc'                               => __( 'user can vote once a year for every rating', 'rating-widget' ),
		'unlimited_desc'                              => __( 'user can vote as many times as their wish', 'rating-widget' ),
		/* Visibility Options
		-----------------------------------------------------------------------*/
		'visibility_title'                            => __( 'Specific Visibility Settings', 'rating-widget' ),
		'visibility__separate-with-commas'            => __( 'Separate ids with commas (e.g. "3,17,8").', 'rating-widget' ),
		'visibility_show-on-every'                    => __( 'Show on every %s', 'rating-widget' ),
		'visibility_show-on-every-exclude'            => __( 'Show on every %1$s except the listed %2$s', 'rating-widget' ),
		'visibility_show-on-every-include'            => __( 'Show only on the listed %s', 'rating-widget' ),
		/* Add-Ons
		-----------------------------------------------------------------------*/
		'addons_title'                                => __( 'Add Ons for RatingWidget', 'rating-widget' ),
		'addons_thanks-subscribing-mailing-list'      => __( 'Thanks for subscribing to the waiting list - we will let you know when the Add On is ready.', 'rating-widget' ),
		'addons_not-ready'                            => __( "The add-on is still not ready for final use, would you like us to let you know when it's ready? Or just anonymously tell us it's interesting?", 'rating-widget' ),
		'addons_add-to-waiting-list'                  => __( 'Yes - add me to the waiting list', 'rating-widget' ),
		'addons_silent-report'                        => __( 'It\'s just interesting', 'rating-widget' ),
		/* Advanced Settings
		-----------------------------------------------------------------------*/
		'visitor-identification_title'                => __( 'Visitor Identification Method', 'rating-widget' ),
		'visitor-identification_by-cookie'            => __( 'Identify visitor by Cookie / Device.', 'rating-widget' ),
		'visitor-identification_by-cookie_pro-only'   => __( 'Visitor by IP identification is only supported in Professional plan and above.', 'rating-widget' ),
		'visitor-identification_by-ip'                => __( 'Identify visitor by IP / Location.', 'rating-widget' ),
		'visitor-identification_by-ip_for-contests'   => __( 'Especially for Voting Contests', 'rating-widget' ),
		'visitor-identification_by-ip_pro-only'       => __( '(included in Professional Plan)', 'rating-widget' ),
		'visitor-identification_by-social'            => __( 'Social connect is part of our upcoming roadmap, but it\'s not ready yet. Appreciate your patience.', 'rating-widget' ),
		'visitor-identification_by-social_desc'       => __( 'Require connect with Social identity like Facebook and Google connect (Coming soon...).', 'rating-widget' ),
		'flash-dependency'                            => __( 'Flash Dependency', 'rating-widget' ),
		'flash-dependency_enable-desc'                => __( 'Enable Flash dependency (track devices using LSO).', 'rating-widget' ),
		'flash-dependency_disable-desc'               => __( 'Disable Flash dependency (devices with identical IPs won\'t be distinguished).', 'rating-widget' ),
		'mobile-settings'                             => __( 'Mobile Settings', 'rating-widget' ),
		/* User Rating Type Options
		-----------------------------------------------------------------------*/
		'reputational-rating_desc'                    => __( 'Reputational (Pro Feature) - aggregated average of user\'s rated elements.', 'rating-widget' ),
		'standard-rating_desc'                        => __( 'Standard - directly affected by rating user\'s profile page.', 'rating-widget' ),
		'reputational-rating_pro-only-alert'          => __( 'User Reputational ratings are only supported in the Professional plan.', 'rating-widget' ),
		/* Upgrade Sidebar Widget
		-----------------------------------------------------------------------*/
		'upgrade_why'                                 => __( 'Why Go Professional?', 'rating-widget' ),
		'upgrade_rich-snippets'                       => __( 'Google Rich Snippets (schema.org)', 'rating-widget' ),
		'upgrade_analytics'                           => __( 'Advanced Ratings\' Analytics', 'rating-widget' ),
		'upgrade_white-labeled'                       => __( 'White-labeled - No Branding', 'rating-widget' ),
		'upgrade_bbpress-forum-topics'                => __( 'bbPress Forum Ratings', 'rating-widget' ),
		'upgrade_ip-identification'                   => __( 'Voting Contests: Visitor by IP identification', 'rating-widget' ),
		'upgrade_custom-design'                       => __( 'Custom Ratings Image', 'rating-widget' ),
		'upgrade_unlimited-criteria'                  => __( 'Unlimited Multi-Criterion', 'rating-widget' ),
		'upgrade_reputation-rating'                   => __( 'User Reputation for BuddyPress / bbPress', 'rating-widget' ),
		'upgrade_priority-email'                      => __( 'Priority Email Support', 'rating-widget' ),
		'upgrade_ssl'                                 => __( 'SSL Support', 'rating-widget' ),
		'upgrade_secure-connection'                   => __( 'Secure Connection (Fraud protection)', 'rating-widget' ),
		'upgrade_wpml'                                => _x( 'WPML Language Auto-Selection', 'WPML is a plugin for multi-lingual support', 'rating-widget' ),
		/* Rich-Snippets Admin Widget
		-----------------------------------------------------------------------*/

		'rich-snippets_marketing'                     => __( 'Show off your ratings in organic search results with Google Rich Snippets! Rich Snippets are proven to increase CTR, sending high quality traffic to your store.', 'rating-widget' ),
		'disclaimer-uppercase'                        => __( 'DISCLAIMER', 'rating-widget' ),
		'rich-snippets_disclaimer'                    => __( 'We have many customers which have the ratings shown in Google SERP (Search Engine Results Page). We follow Google\'s best practices and constantly improve the plugin according to the newest updates to make
				sure that your pages will pass %s. But, %s. Why? Unfortunately we don\'t have access nor control of Google\'s algorithms. The algorithm which decides whether to show the stars (or not) is based on the search keywords, page popularity, device type, country and many more variables. Our recommendation: if you are willing to risk one month of payment for the Professional plan, upgrade, and give it between 2-3 weeks to see if Google "liked" your site. If the ratings will be synced with the search results - AWESOME! If not, simply downgrade back to the Free version. Note - there won\'t be any refunds for claims about the Rich-Snippets.', 'rating-widget' ),
		'rich-snippets_testing-tool'                  => __( 'Google\'s official rich snippets testing tool', 'rating-widget' ),
		'rich-snippets_disclaimer-bold'               => __( 'we can NOT assure that Google will show your stars in the search results', 'rating-widget' ),
		/* Power-User Settings
		-----------------------------------------------------------------------*/
		'power-user-settings'                         => __( 'Power User Settings', 'rating-widget' ),
		/* Post Views Visibility Settings
		-----------------------------------------------------------------------*/
		'post-views-settings'                         => __( 'Post Views Visibility Settings', 'rating-widget' ),
		/* Metabox Settings
		-----------------------------------------------------------------------*/
		'uncheck-to-hide'                             => __( 'Un-check to Hide', 'rating-widget' ),
		'uncheck-to-readonly'                         => __( 'Un-check for ReadOnly', 'rating-widget' ),
		/* Comment Ratings Mode
		-----------------------------------------------------------------------*/

		'comment-ratings-mode'                        => __( 'Comment Ratings Mode', 'rating-widget' ),
		'comment-ratings-mode_standard'               => __( 'Comment Ratings - Users can vote each other\'s comments.', 'rating-widget' ),
		'comment-ratings-mode_reviews'                => __( 'Reviews Ratings - Users can submit a rating with their comments.', 'rating-widget' ),
		'comment-ratings-mode_author'                 => __( 'Moderator Ratings - Only admin users can rate the comments [via the comment editor].', 'rating-widget' ),
		/* Categories Visibility Settings
		-----------------------------------------------------------------------*/

		'categories-visibility-settings'              => __( 'Categories Visibility Settings', 'rating-widget' ),
		'all-categories'                              => __( 'All Categories', 'rating-widget' ),
		/* User Availability Settings
		-----------------------------------------------------------------------*/
		'user-availability-settings'                  => __( 'User Availability Settings', 'rating-widget' ),
		'user-availability-settings_all'              => _x( 'Show active %s ratings for all users.', '%s - ratings types, e.g. "post and comment"', 'rating-widget' ),
		'user-availability-settings_disable-unlogged' => __( 'Disable %s ratings for unlogged users.', 'rating-widget' ),
		'user-availability-settings_hide-unlogged'    => __( 'Hide %s ratings from unlogged users.', 'rating-widget' ),
		/* TinyMCE Top-Rated Table
		-----------------------------------------------------------------------*/
		'toprated-table-win_title'                    => __( 'Add Top-Rated Table', 'rating-widget' ),
		'table-options'                               => __( 'Table Options', 'rating-widget' ),
		'direction'                                   => _x( 'Direction', 'Left to right or Right to left', 'rating-widget' ),
		'ltr'                                         => __( 'Left to Right', 'rating-widget' ),
		'rtl'                                         => __( 'Right to Left', 'rating-widget' ),
		'min-votes'                                   => _x( 'Min Votes', 'min count of votes', 'rating-widget' ),
		'max-items'                                   => _x( 'Max Items', 'max number of items', 'rating-widget' ),
		'votes-number'                                => __( 'Votes Number', 'rating-widget' ),
		'likes-for-thumbs'                            => __( 'Likes (for Thumbs)', 'rating-widget' ),
		'add-table'                                   => __( 'Add Table', 'rating-widget' ),
		'add-table_shortcode-desc'                    => __( 'Note: After clicking "Add Table", a special shortcode will be added to your editor. It would be rendered as a beautiful table only in your site.', 'rating-widget' ),
		/* Periods
		-----------------------------------------------------------------------*/
		'all-time'                                    => __( 'All Time', 'rating-widget' ),
		'last-year'                                   => __( 'Last Year', 'rating-widget' ),
		'last-x-months'                               => __( 'Last %d Months', 'rating-widget' ),
		'last-x-days'                                 => __( 'Last %d Days', 'rating-widget' ),
		'last-x-hours'                                => __( 'Last %d Hours', 'rating-widget' ),
		/* Plugin Deactivation
		-----------------------------------------------------------------------*/
		'deactivation-confirm-message'                => __( 'Just a heads up - your site currently has %d ratings and %d votes. If you are about to delete the plugin after the deactivation you will lose all that data. Are you sure that you would like to proceed?', 'rating-widget' ),
		/* Workflows
		-----------------------------------------------------------------------*/
		'workflows'                                   => __( 'Workflows', 'rating-widget' ),
		'template-variables'                          => __( 'Template Variables', 'rating-widget' ),
		'template_vote'                               => __( 'The vote given by the user. e.g.: 5-star', 'rating-widget' ),
		'template_avg-rate'                           => __( 'The average rating value. e.g.: 4.5', 'rating-widget' ),
		'template_title'                              => __( 'The title of the current post.', 'rating-widget' ),
		'workflows_get-started'                       => __( 'Get started with Workflows', 'rating-widget' ),
		'new-workflow'                                => __( 'New Workflow', 'rating-widget' ),
		'workflows_change-order'                      => __( 'To change the order, drag the target workflow and drop into the desired position.', 'rating-widget' ),
		'conditions'                                  => __( 'Conditions', 'rating-widget' ),
		'actions'                                     => __( 'Actions', 'rating-widget' ),
		'events'                                      => __( 'Events', 'rating-widget' ),
		'workflow-name'                               => __( 'Workflow Name', 'rating-widget' ),
		'next-step'                                   => __( 'Next Step', 'rating-widget' ),
		'saving'                                      => __( 'Saving...', 'rating-widget' ),
		'update-name'                                 => __( 'Update Name', 'rating-widget' ),
		'update-conditions'                           => __( 'Update Conditions', 'rating-widget' ),
		'update-actions'                              => __( 'Update Actions', 'rating-widget' ),
		'update-events'                               => __( 'Update Events', 'rating-widget' ),
		'view-all-workflows'                          => __( 'View all Workflows', 'rating-widget' ),
		'and'                                         => _x( 'And', 'conjunction', 'rating-widget' ),
		'or'                                          => _x( 'Or', 'conjunction', 'rating-widget' ),
		'if'                                          => _x( 'If', 'conjunction', 'rating-widget' ),
		'then'                                        => _x( 'Then', 'as after that; next; afterward', 'rating-widget' ),
		'when'                                        => __( 'When', 'rating-widget' ),
		'is'                                          => __( 'is', 'rating-widget' ),
		'is-not'                                      => __( 'is-not', 'rating-widget' ),
		'is-equal-to'                                 => __( 'is equal to', 'rating-widget' ),
		'is-less-than'                                => __( 'is less than', 'rating-widget' ),
		'is-less-than-or-equal-to'                    => __( 'is less than or equal to', 'rating-widget' ),
		'is-greater-than'                             => __( 'is greater than', 'rating-widget' ),
		'is-greater-than-or-equal-to'                 => __( 'is greater than or equal to', 'rating-widget' ),
		'votes-count'                                 => __( 'Votes Count', 'rating-widget' ),
		'current-star-vote'                           => __( 'Current Star Vote', 'rating-widget' ),
		'current-thumbs-vote'                         => __( 'Current Thumbs Vote', 'rating-widget' ),
		'invalid-workflow-name'                       => __( 'Invalid Workflow Name', 'rating-widget' ),
		'addon-settings'                              => __( 'Add-On Settings', 'rating-widget' ),
		'no-workflows-to-load'                        => __( 'No workflows to load', 'rating-widget' ),
		'workflows-processed-top-to-bottom'           => __( 'All workflows, processed from top to bottom', 'rating-widget' ),
		'workflow-delete-confirm'                     => __( 'Are you sure you would like to delete this workflow?', 'rating-widget' ),
		'after-vote'                                  => __( 'After Vote', 'rating-widget' ),
		'before-vote'                                 => __( 'Before Vote', 'rating-widget' ),
		/*
		-----------------------------------------------------------------------*/
		'ok-i-am-in'                                  => __( "OK - I'm in!", 'rating-widget' ),
		'tweets-promotion_title'                      => __( 'Tweets Add-On is here!', 'rating-widget' ),
		'tweets-promotion_msg'                        => __( 'Increase your social traffic by asking your visitors to Tweet the post after submitting a 5-star rating.' )
	);
